### ISSUE TITLE
saving marked labels as text

### ISSUE THREAD

**Issue by heikotree** [rambaut/figtree#107]
It would be nice if one could save (or copy and paste) marked labels as text.

Currently, one can save/copy the structure of a subtree (induced by marked nodes in the tree) as NEWICK, however, for comparison of taxa/sequences e.g. contained in clades of different trees, it would be nice to be able to extract the labels alone.

Cheers,
Heiko

**Comment by heikotree** [comment]
Hi Andrew,

that would be great, but as it looks the induced subtree is copied.

For instance, if I load the tree ((A:0.1,B:0.1):0.1,(C:0.1,D:0.1):0.1);

and I select the leafs A and C, than copy and paste to an editor produces:

---------------
#NEXUS
begin trees;
	tree tree_1 = [&R] (A:0.2,C:0.2);
end;
---------------

This is regardless of whether Node, Clade or Taxa mode is selected :(

I was trying with 1.4.2 on my Mac.


A typical application would be to select the rooting branch of a subtree and than copy the names of all names of the selected leafs (sometimes after unselecting a few). If changing the mode between Clade and Taxa mode would be required that would be fine with me… 

Best wishes,
Heiko

**Comment by rambaut** [comment]
Yes - I haven't implemented it yet. I was just saying it would be logical if this was the behaviour.

**Comment by heikotree** [comment]
He said and closed the issue ;)

Yes indeed, that behaviour would be logical!
(I had thought you meant to say that it should have shown that behaviour anyway… and wrong I was)

Cheers,
Heiko

**Comment by buczek** [comment]
Heiko, can you remove the @molgen.mpg.de email address from your github.com account? It has been recycled after several years and the new owner got your github notifications of this issue. Thanks &  all the best -- Donald
