### ISSUE TITLE
import annotation does not work?

### ISSUE THREAD

**Issue by ghost** [rambaut/figtree#123]
WHEN I IMPORT ANNOTATIONS INTO FIGTREE FOR TIP SHAPES, AND WNAT TO COLOR BY THE IMPORTED ANNOTATIONS, NOTHING HAPPENED?

**Comment by ZooPhy** [comment]
Same thing happened to me. Not sure if it is a bug.

**Comment by ZooPhy** [comment]
It works for me. It helps if you run it in java and then you can check the console when you try to import to see if it causes an Exception.

**Comment by BEAST-Community** [comment]
@ZooPhy That's great, could I get your email for the details, thanks.

**Comment by ZooPhy** [comment]
simply run: java -jar figtree.jar and it will launch the GUI but keep the terminal open.

**Comment by BEAST-Community** [comment]
@ZooPhy can you custom colors?
