### ISSUE TITLE
How can I cite Figtree

### ISSUE THREAD

**Issue by freddymonteiro** [rambaut/figtree#130]
Is there any publication, or just a link to the github repository / website is enough?
Freddy

**Comment by SilentGene** [comment]
Yes, just cite "http://tree.bio.ed.ac.uk/software/figtree/" is ok based on my experience.

**Comment by lianzhengli** [comment]
so, who is the author?…

**Comment by RieLuc23** [comment]
That is not enough.... Is there an author for citation in APA format??
