### ISSUE TITLE
Text in trees displayed as blocks

### ISSUE THREAD

**Issue by DeondeJager** [rambaut/figtree#144]
Hi,

I've produced some trees using MrBayes v3.2.6, which produces trees in Figtree format by default, but when I open the con.tre file in Figtree, the text (e.g. tip labels) are just displayed as black blocks (see image below). I tried opening .tree files from BEAST that have opened without this problem in the past (in March 2019) and the same thing happens where the text is displayed as blocks. 

So to me, it looks like a font issue of sorts, perhaps introduced after a Windows update. I'm on Windows 10 Pro Version	10.0.17134 Build 17134. I have the same problem with both Figtree v1.4.4 and v1.4.3. I opened the con.tre file in Figtree v1.4.3 on another computer running Windows 7 and the text displays correctly. 

Has anyone else reported this issue? Do you have any ideas on how to get around it?

<img width="958" alt="Figtree1" src="https://user-images.githubusercontent.com/10435758/65772168-ffa68780-e139-11e9-89b7-1dfdc6874790.png">

**Comment by jumanaghmno9** [comment]
hi did you solve the problem ? i really need to know how
