### ISSUE TITLE
Cannot save as tree into Pdf and SVG file

### ISSUE THREAD

**Issue by edwinsetiawan671** [rambaut/figtree#168]
Is anybody understands why I couldn't export my tree into pdf or SVG file? Strange that it just happened a few days ago until now.
See that save as SVG and pdf are disappear. I use windows 10 and JavaSetup8u281 and Figtree  v.144. 
![Fig_1](https://user-images.githubusercontent.com/61499707/113963231-6c343380-9853-11eb-9595-3e83937a5f3f.jpeg)
![Fig_2](https://user-images.githubusercontent.com/61499707/113963234-6dfdf700-9853-11eb-95e8-5d8cf79fe96c.jpeg)

Looking forward to having some suggestion

**Comment by Neo-sage** [comment]
If you click File then go to Export PDF, does it work?

**Comment by lly1214** [comment]
Did you solve your problem?
I click File then go to Export PDF, and there is no response.

**Comment by lly1214** [comment]
> If you click File then go to Export PDF, does it work?

I click File then go to Export PDF, and there is no response.

**Comment by edwinsetiawan671** [comment]
Yes. Now it is working

Many thanks for your help

Best

Edwin
