### ISSUE TITLE
same MCC tree displays differently 

### ISSUE THREAD

**Issue by ctob2** [rambaut/figtree#169]
Hello
When I load an MCC tree it is giving a very different root date/MRCA to when a colleague does. 
We are both using figtree 1.4.4 and for the beast outputs 1.10.4.
The MCC tree was made in tree annotator (from a combined tree file made in log combiner).
the other oddity is that when i click 'show gridlines' none display.
I do have figtree 1.4.2 still on ym mac and wonder if that could be an issue?
or can you advise?
much obliged, thank you
Camilla

**Comment by rambaut** [comment]
It is not possible to address this without the example files.
