### ISSUE TITLE
FigTree 1.4.4 does not find Java on apple M1 Big Sur

### ISSUE THREAD

**Issue by cdoorenweerd** [rambaut/figtree#173]
Launching FigTree v1.4.4 gives a pop-up:

ERROR launching 'FigTree v1.4.4'.

No suitable Java version found on your system!
This program requires Java  6 or later.
Make sure you install the required Java version.

But I have java installed:

(base) cdoorenweerd@Camiels-MacBook-Pro-2 ~ % java -version
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Zulu16.32+15-CA (build 16.0.2+7)
OpenJDK 64-Bit Server VM Zulu16.32+15-CA (build 16.0.2+7, mixed mode)

trying on a macbook pro M1, 2020, Big Sur 11.5.2

any clues would be appreciated, FigTree is of great help with my work!

**Comment by cdoorenweerd** [comment]
of course, after struggling with this for weeks, five minutes after posting the issue I find a workaround:

If I alt-click on the .app in the applications folder and 'show package contents', go to Contents > Resources > Java, starting FigTree with the  figtree.jar in that folder works.

**Comment by cdoorenweerd** [comment]
the workaround put me on the path to a fix;

in the FigTree app (show package contents), replace the universalJavaApplicationStub file with a newer version from https://github.com/tofi86/universalJavaApplicationStub/releases/ . I used v3.2.0 for MacOS v11. This will enable the FigTree.app executable to find java (again)

**Comment by rvosa** [comment]
Hi Camiel,

thanks for figuring this out - hope you are well :-)

Rutger

**Comment by rambaut** [comment]
Updating universalJavaApplicationStub fixes this issue and will be in the future release (or can be replaced manually as described above).

**Comment by c-m-gibbs** [comment]
Hey @lilly121, not sure if this is helpful to you... I didn't replace the JavaApplicationStub but I found it worked if I just double-clicked it. It opened a new instance of terminal and then the FigTree GUI, which works as normal.

Applications > right-click FigTree v1.4.4 > show package contents > Contents > MacOS > double-click universalJavaApplicationStub
