### ISSUE TITLE
Error: Unable to access jarfile lib/figtree.jar

### ISSUE THREAD

**Issue by B-1991-ing** [rambaut/figtree#177]
Dear figtree support team,

I am trying to open my tree in figtree using command lines as shown below, but error happened. Could you give me some suggestions?

**command lines** 
#module load jdk/18.0.1
#module load openjdk/18.0.1
#module load java/1.7.0
#module load jre/1.8.0
#module load figtree/1.4.4
#module load /cm/local/.modulefiles_cache/tools/modulefiles/figtree/1.4.4
#figtree /home/projects/env_10000/people/binson/Previous_pipeline/de_novo_wf/infer/gtdbtk.bac120.decorated.tree

**Error: Unable to access jarfile lib/figtree.jar**
<img width="729" alt="Screenshot 2022-04-30 at 23 48 36" src="https://user-images.githubusercontent.com/54441633/166123753-10a5838b-3c80-485d-8496-9217e8b49542.png">

Thank you very much.

Best,

Bing

**Comment by B-1991-ing** [comment]
Dear figtree support team,

**Update**

After google and read some related problems and answers, eg.,  **java exception #176**.

I tried to login to the HPC cluster with **"ssh -X"(not okay for me)** and **"ssh -Y"(okay for me)**. And, then entered the below command lines, it worked. 

module load jdk/18.0.1
module load openjdk/18.0.1
module load java/1.7.0
module load jre/1.8.0
module load figtree/1.4.4
java -jar /services/tools/figtree/1.4.4/lib/figtree.jar 
#Then, open my tree file

Hope it gives others some hints.

Best,

Bing

**Comment by rambaut** [comment]
This seems to be specific to the platform/machine it is being run on.

**Comment by janikkokot** [comment]
I have encountered the same issue on Ubuntu.

I was able to fix it by changing the `lib/figtree` part at the end of the java command in `bin/figtree` from relative path to the absolute path.


This should also work irrespective of installation location.

```sh
#!/bin/sh
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

java -Xms64m -Xmx512m -jar ${SCRIPT_DIR}/../lib/figtree.jar "$@"
```
