### ISSUE TITLE
Cannot export tree images on macos

### ISSUE THREAD

**Issue by TAKosch** [rambaut/figtree#179]
Hello,

I was using figtree and it was working great. I used it to export several trees in PNG format and then suddenly nothing happens when I select export > PNG. I tried reinstalling the program and restarting my computer, but nothing allows me to export images again. My OS is mac Monterrey.

Thanks,
Tiffany

**Comment by rambaut** [comment]
I think the PNG export library is no longer working. On a Mac the easiest thing is to "Export to PDF..." then load the PDF into Preview.app and export as PNG from there.

**Comment by jmperillal** [comment]
I'm having the same issue when I try to export PDF/SVG/PNG/JPG. I tried using mac and windows devices but nothing happens when I select these options.

**Comment by rambaut** [comment]
Unable to replicate.
