### ISSUE TITLE
Incorrect matching of tips to annotation 

### ISSUE THREAD

**Issue by AntonS-bio** [rambaut/figtree#184]
Hi, 

I've noticed that when the annotation file contains empty cells (these are labelled "Unknown" in valid file, but are blank in invalid one), the Figtree doesn't correctly match the tips to the annotation. For example, using attached files the leaf "M94957.1" is labelled "Unknown" if valid metadata file is used, but labelled "United Kingdom: England" if invalid one is used. The specific mislabelling might be different on your machine, but in this small tree it's quite easy to spot. 

[LouipingIllMetaData_invalid.txt](https://github.com/rambaut/figtree/files/9777237/LouipingIllMetaData_invalid.txt)
[LouipingIllMetaData_valid.txt](https://github.com/rambaut/figtree/files/9777238/LouipingIllMetaData_valid.txt)
[louping_ill_tree.txt](https://github.com/rambaut/figtree/files/9777239/louping_ill_tree.txt)

**Comment by rambaut** [comment]
Fixed
