### ISSUE TITLE
FigTree says "Missing closing ')' in tree" when there isn't one

### ISSUE THREAD

**Issue by shbrainard** [rambaut/figtree#187]
I built a tree in MEGA11 using ML and 100 iterations to estimate bootstrap values.  FigTree complains there is a missing parentheses in the output Newick file, but there isn't one:

`
((((((((((Chet_BJ_EVM0006124,Chet_JL_Cor0014550.1,Cav_TGdL_Haze_02754)0.6900,Cam_g3412)1.0000,(Cav_TGdL_Haze_07943,Chet_JL_Cor0163760.1)1.0000,(Osat_10g41130.1,(Osat_04g46440.1,Osat_02g43970.1)1.0000)0.6200,Osat_04g46400.1,Chet_JL_Cor0156810.1,((Chet_BJ_EVM0011762,Cav_Tom_Cav07g13740)1.0000,(((Chet_JL_Cor0193550.1,Cav_Tom_Cav11g13170)0.7200,Cav_TGdL_Haze_25802)1.0000,(Chet_JL_Cor0051550.1,(Cav_TGdL_Haze_21884,Cam_g24838)0.8900)1.0000)0.8000)0.9600)0.9700,((Cav_TGdL_Haze_08951,Cav_Tom_Cav03g18670)1.0000,((Chet_BJ_EVM0013717,Cman_G0007739)0.5200,Cam_g26066,(Cav_Tom_Cav09g01740,Cav_TGdL_Haze_19546)0.6100)1.0000)0.9500)0.9900,(Osat_01g73770.1,((Cav_Tom_Cav10g05610,Chet_BJ_EVM0021922,Cman_G0012172)1.0000,(Cav_TGdL_Haze_19557,Chet_BJ_EVM0020113,(Cav_Tom_Cav09g01950,Cman_G0007747)0.5200)1.0000)0.7900)0.5400)0.7900,((Osat_04g48350.1,Osat_02g45450.1)1.0000,(Osat_06g03670.1,Osat_09g35030.1)0.5900)0.9600)0.6700,(At_CBF3,(At_CBF1,At_CBF2)0.7900)1.0000)0.9400,((((Bpen_c2812,Bpen_c0079_dupelabel1)0.8000,Bpen_c0079)0.7200,(Bpen_c0075_dupelabel1,Bpen_c0075)0.9400)0.9000,(Cman_G0014289,(Cman_G0014293,Cman_G0014291)0.5600,(Cam_g17287,((Cav_Tom_Cav05g12880,Cav_TGdL_Haze_13764)0.7000,Cam_g17283)0.5000,(Chet_BJ_EVM0003046,Chet_JL_Cor0119160.1)0.9300,(Chet_JL_Cor0119170.1,Cam_g17285,Chet_BJ_EVM0011084,(Cav_Tom_Cav05g12910,Cav_Tom_Cav05g12900)0.6300)0.5400)0.5000)1.0000)0.9900)1.0000,((Bpen_c0278_dupelabel3,Bpen_c0278_dupelabel2)0.6300,(Bpen_c0278,Bpen_c0278_dupelabel1)1.0000)0.8800)0.9300,Cav_TGdL_Haze_08953,(Cam_g10983,Cman_G0022097,Chet_JL_Cor0080960.1,Cav_Tom_Cav03g18710)0.8500((Cav_Tom_Cav03g18700,Cam_g10982,Chet_BJ_EVM0013486,Cav_Tom_Cav03g18690)0.7200,Cman_G0022096)0.9800,(((Chet_BJ_EVM0008440,Cman_G0022095)0.6200,Chet_JL_Cor0080950.1)0.7700,Cam_g10981,(Cman_G0022094,((Cav_TGdL_Haze_08952,Cav_Tom_Cav03g18680)0.7500,(Cam_g10980,(Chet_BJ_EVM0017023,Chet_JL_Cor0080940.1)0.8200)0.6900)0.8500)0.9900)0.6200);`

This file works fine in other viewers, but I like FigTree, and would prefer to use it if I can figure out what's going on.

**Comment by rambaut** [comment]
This file is missing a comma between two clades: 
`,Cav_Tom_Cav03g18710)0.8500((Cav_Tom_Cav03g18700,`
