### ISSUE TITLE
Mac version cannot start

### ISSUE THREAD

**Issue by walterxie** [rambaut/figtree#188]
Download the latest version `FigTree.v1.4.4.dmg`, click the app, and an err message popped out "No suitable Java found". My macOS is Ventura 13.2.1 using M1 chip. I tried all Java versions below, none works. I could be wrong, but I suspect it is the issue of universalJavaApplicationStub [function is_valid_requirement_pattern() {](https://github.com/rambaut/figtree/blob/f9085b63d94fccdfa765283d936a5f17f0253175/packaging_tools/mac/universalJavaApplicationStub#L532).  

We have to use "Java executable version" (FigTree_v1.4.4.tgz) for teaching at the moment.

**The same issue of TempEst Mac version.**

```bash
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (5):
    19 (arm64) "Oracle Corporation" - "Java SE 19" /Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home
    18.0.2 (arm64) "Oracle Corporation" - "OpenJDK 18.0.2" /Library/Java/JavaVirtualMachines/jdk-18.0.2.jdk/Contents/Home
    17.0.5 (x86_64) "Azul Systems, Inc." - "Zulu 17.38.21" /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
    17.0.2 (arm64) "Oracle Corporation" - "OpenJDK 17.0.2" /Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home
    1.8.0_292 (x86_64) "AdoptOpenJDK" - "AdoptOpenJDK 8" /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
```

```bash
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

<img width="532" alt="Screenshot 2023-03-21 at 8 43 58 AM" src="https://user-images.githubusercontent.com/5743014/226449754-0487ea93-1f20-4c06-83d9-2ecd426b7f27.png">

**Comment by joelclim** [comment]
FigTree seems to be looking for JAVA_HOME. A work around I found is to run the application via the command line.

Here are the steps that worked for me. 

1. Copy FigTree v1.4.4 to `/Applications`.
2. Open Terminal
3. Make sure JAVA_HOME is set in your `~/.bashrc` and/or `~/.bash_profile`.
```
export JAVA_HOME=$(/usr/libexec/java_home)
```
4. Exit Terminal
5. Open Terminal (again)
6. Run FigTree from the command line.
```
$ open `/Applications/FigTree\ v1.4.4.app/`
```

Hope this helps.

**Comment by flodebarre** [comment]
In case someone else ends up here while trying to install FigTree v.1.4.4 on a Mac and failing: you do need to have `openJDK` on your computer. The fix does not work with the original java version installed on your machine (check the output of `$ java -version`). 

To install openJDK, in a terminal, type
```
$ brew install openjdk
```
(If you do not already have `homebrew`, you can install it by following the instructions on [this page](https://brew.sh).)

Then, as suggested in the message displayed when the program stops running, you need to type
```
$ sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
```
to actually change the java version on your machine. You can check whether you have correctly changed it via `$ java -version`. 

Then restart your computer, and follow the instructions proposed above.

**Comment by Namrata2801** [comment]
I tried both the approaches mentioned above but I am still getting the same error. Any help would be appreciated.

**Comment by rambaut** [comment]
I have posted new executables to [https://github.com/rambaut/figtree/releases/tag/v1.4.5pre](https://github.com/rambaut/figtree/releases/tag/v1.4.5pre) in which I have updated all the packaging scripts for Windows and Mac. I am going to close this issue and new ones can be opened with regard to these new executables.
