### ISSUE TITLE
Displaying Orthofinder's species Tree

### ISSUE THREAD

**Issue by J-Calvelo** [rambaut/figtree#190]
Hello. I'm having trouble understanding where some values come from. When I try to display a species tree created with orthofinder Fig tree display several values associated with each node:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/19414181/235377401-91b94278-cc4f-47f2-902d-bbfb2504732e.png">

But as far I can tell they are not present on the original text file:
(Elysia_marginata_GCA_019649035.1:0.31036,(Bulinus_truncatus_GCA_021962125.1:0.234925,(Biomphalaria_straminea_gigascience:0.0673267,(((Biomphalaria_glabrata_iBS90_GCA_025434165.1:0.0147311,Biomphalaria_glabrata_IM_GCA_025434175.1:0.0182529)0.274249:0.0209925,Biomphalaria_glabrata_VectorBaseBB02:0.0479956)0.339224:0.0159541,(Biomphalaria_pfeifferi_SamTeam:0.0258237,Biomphalaria_sudanica:0.0253159)0.352635:0.0177205)0.388502:0.0383117)0.735316:0.145343)1:0.31036);

from where are these numbers comming from?

**Comment by JGLAHE** [comment]
![Untitled](https://user-images.githubusercontent.com/86393993/235457362-55af06a5-99e5-40b7-b244-cc4c40ff9dba.png)

Each of the sidebar options expands by clicking the grey triangles (e.g. circled in red). You're dsiplaying the default node label value, which is Node ages. Typically you'd click the Display drop-down menu (red arrow) and select the last option 'label' to display whatever labels you'd already included in your tree file e.g. SHaLRT/BS/PP/..., etc
