### ISSUE TITLE
Scary warning message when opening in MacOS 11 (Big Sur)

### ISSUE THREAD

**Issue by zygoballus** [rambaut/figtree#195]
I just installed FigTree v1.4.4 for MacOS via the disk image at https://github.com/rambaut/figtree/releases/tag/v1.4.4. Upon trying to open the program for the first time, it gives me the warning message:

“bash” wants access to control “System Events”. Allowing control will provide access to documents and data in “System Events”, and to perform actions within that app.

It gives me the option to Allow or Don't Allow, and because it's a rather scary sounding warning, I chose Don't Allow, which prevents the program from launching. Why does opening FigTree trigger bash to need access to System Events? Should I allow it?

**Comment by rambaut** [comment]
Updated to latest Mac executable script which should fix this. Test downloads available here: [https://github.com/rambaut/figtree/releases/tag/v1.4.5pre](https://github.com/rambaut/figtree/releases/tag/v1.4.5pre). Closing this issue - it can be reopened if still happening with these new executables.
