### ISSUE TITLE
official release?

### ISSUE THREAD

**Issue by kwongj** [rambaut/figtree#99]
Thanks for all the changes! I particularly like the ability to select node shapes for either internal or external nodes.

Just wondering if there will be a formal release eg. mac OSX install package etc. in the near future?

**Comment by rambaut** [comment]
Thanks for the feed back. There will be an official release as soon as I have time to fix a few more things. There is 
a packaged pre-release here:

https://github.com/rambaut/figtree/releases

A.

> On 27 Oct 2015, at 10:09, Jason Kwong <notifications@github.com> wrote:
> 
> Thanks for all the changes! I particularly like the ability to select node shapes for either internal or external nodes.
> 
> Just wondering if there will be a formal release eg. mac OSX install package etc. in the near future?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/rambaut/figtree/issues/99>.
> 

Andrew Rambaut 
Institute for Evolutionary Biology | Centre for Infection, Immunity & Evolution 
Ashworth Laboratories, University of Edinburgh, Edinburgh, EH9 3FL, UK

contact – a.rambaut@ed.ac.uk <mailto:a.rambaut@ed.ac.uk> | http://tree.bio.ed.ac.uk <http://tree.bio.ed.ac.uk/> | tel +44 131 6508624


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
